[tool.poetry]
name = "vonoben"
version = "0.1"
description = ""
authors = []


[tool.poetry.dependencies]
python = "^3.8"
mypy = "^0.782"
pylint = "^2.5.3"
scrapy = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
